# Generated by Django 5.0.3 on 2024-03-11 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='icon',
            field=models.ImageField(default='', upload_to='pics'),
        ),
    ]
