# Generated by Django 5.0.5 on 2024-05-13 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('play_instruction', models.TextField()),
                ('version', models.IntegerField()),
                ('per_person_cost', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
